# Return the custom response generated by Paypal APIS
# Inherited from StandardError
class KsResponse < StandardError
	attr_accessor :ks_response 

	def initialize(ks_response)
		@response_array = []
		@ks_response = ks_response
	end 

	def ks_success_messages
		@response_array << ks_response
		response = {success: true ,response:@response_array}
	end
end